CREATE SEQUENCE USER_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 10000;

create table USERS(
  USER_ID       NUMBER(32) DEFAULT USER_SEQ.NEXTVAL
    CONSTRAINT PK_USER_ID PRIMARY KEY,
  PASSWORD      VARCHAR2(255)                                  NOT NULL,
  LOGIN_ID      VARCHAR2(32)                                   NOT NULL
    CONSTRAINT UK_LOGIN_ID UNIQUE,
  NAME          VARCHAR2(64),
  EMAIL         VARCHAR2(64),
  CREATED_BY    VARCHAR(32) DEFAULT 'system'                   NOT NULL,
  CREATED_DATE  TIMESTAMP(6) DEFAULT current_timestamp         NOT NULL,
  DISABLED      VARCHAR2(1) default 'N'                        NOT NULL
);